const {
  REACT_APP_OPEN_WEATHER_API,
  REACT_APP_API_OPEN_WEATHER_ICON_URL,
  REACT_APP_OPEN_WEATHER_KEY,
} = process.env;

export const API_URL = REACT_APP_OPEN_WEATHER_API;
export const ICON_URL = REACT_APP_API_OPEN_WEATHER_ICON_URL;
export const API_KEY = REACT_APP_OPEN_WEATHER_KEY;
